import Topbar from "@/Components/Home";
import ShowFiles from "@/Components/Showfile";
import UploadFiles from "@/Components/UploadFiles/UploadFiles";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <div className="bg-red-400"> */}
          <Topbar/>
          <UploadFiles/>
          <ShowFiles/>
          {/* </div> */}
        </div>
      </main>
    </>
  );
}
